/*
	Copyright (c) 2022-2025, The igLibrary Contributors.
	igLibrary and its libraries are free software: You can redistribute it and
	its libraries under the terms of the Apache License 2.0 as published by
	The Apache Software Foundation.
	Please see the LICENSE file for more details.
*/


namespace igLibrary.Gfx
{
	public enum IG_GFX_TEXTURE_FILTER : int
	{
		IG_GFX_TEXTURE_FILTER_NEAREST = 0,
		IG_GFX_TEXTURE_FILTER_NEAREST_MIPMAP_NONE = 0,
		IG_GFX_TEXTURE_FILTER_LINEAR = 1,
		IG_GFX_TEXTURE_FILTER_LINEAR_MIPMAP_NONE = 1,
		IG_GFX_TEXTURE_FILTER_NEAREST_MIPMAP_NEAREST = 2,
		IG_GFX_TEXTURE_FILTER_NEAREST_MIPMAP_LINEAR = 3,
		IG_GFX_TEXTURE_FILTER_LINEAR_MIPMAP_NEAREST = 4,
		IG_GFX_TEXTURE_FILTER_LINEAR_MIPMAP_LINEAR = 5,
		IG_GFX_TEXTURE_FILTER_ANISOTROPIC = 6,
		IG_GFX_TEXTURE_FILTER_ANISOTROPIC_MIPMAP_NONE = 6,
		IG_GFX_TEXTURE_FILTER_ANISOTROPIC_MIPMAP_NEAREST = 7,
		IG_GFX_TEXTURE_FILTER_ANISOTROPIC_MIPMAP_LINEAR = 8,
	}
}