<!--
	Copyright (c) 2022-2025, The igCauldron Contributors.
	igCauldron and its libraries are free software: You can redistribute it and
	its libraries under the terms of the Apache License 2.0 as published by
	The Apache Software Foundation.
	Please see the LICENSE file for more details.
-->

<Project Sdk="Microsoft.NET.Sdk">

  <!--===================-->
  <!-- Common Properties -->
  <!--===================-->

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <!--============-->
  <!-- References -->
  <!--============-->


  <!-- Project References -->

  <ItemGroup>
    <ProjectReference Include="..\igLibrary\igLibrary.csproj" />
  </ItemGroup>

  <!-- Package References -->

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.89.4" />
    <PackageReference Include="OpenTK" Version="4.7.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
  </ItemGroup>



  <!--===================-->
  <!-- Platform Specific -->
  <!--===================-->

  <!-- Windows Specific -->

  <PropertyGroup Condition=" '$(OS)' == 'Windows_NT' ">
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformConstant>_WINDOWS</PlatformConstant>
  </PropertyGroup>

  <!-- OSX Specific -->

  <!-- Linux Specific -->



  <!--========================-->
  <!-- Configuration Specific -->
  <!--========================-->

  <!-- Debug Specific -->

  <!-- Release Specific -->

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
  </PropertyGroup>

  <!--=======-->
  <!-- Setup -->
  <!--=======-->

  <!-- Apply set variables -->

  <PropertyGroup>
    <DefineConstants>$(PlatformConstant);$(FeatureConstants)</DefineConstants>
  </PropertyGroup>

  <!--==================-->
  <!-- Post Build Tasks -->
  <!--==================-->

  <ItemGroup>
    <ArkFiles Include="../Resources/ArkCore/**" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersImaginators\metaenums.xml" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersImaginators\metafields.xml" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersImaginators\metaobjects.xml" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersSuperchargers\metaenums.xml" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersSuperchargers\metafields.xml" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersSuperchargers\metaobjects.xml" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersTrapTeam\metaenums.xml" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersTrapTeam\metafields.xml" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersTrapTeam\metaobjects.xml" />
    <Content Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersTrapTeam\tfbbindings.xml" />
    <Content Include="bin\Debug\net6.0-windows\igCauldron3.deps.json" />
    <Content Include="bin\Debug\net6.0-windows\igCauldron3.runtimeconfig.json" />
    <DefaultImGuiIni Include="../Resources/defaultimgui.ini" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersImaginators\initscript" />
    <None Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersSuperchargers.ark" />
    <None Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersSuperchargers\initscript" />
    <None Include="bin\Debug\net6.0-windows\ArkCore\EV_SkylandersTrapTeam\initscript" />
    <None Include="bin\Debug\net6.0-windows\dxt1.dat" />
    <None Include="bin\Debug\net6.0-windows\HashDepot.dll" />
    <None Include="bin\Debug\net6.0-windows\igCauldron3.dll" />
    <None Include="bin\Debug\net6.0-windows\igCauldron3.exe" />
    <None Include="bin\Debug\net6.0-windows\igCauldron3.pdb" />
    <None Include="bin\Debug\net6.0-windows\igLibrary.dll" />
    <None Include="bin\Debug\net6.0-windows\igLibrary.pdb" />
    <None Include="bin\Debug\net6.0-windows\ImGui.NET.dll" />
    <None Include="bin\Debug\net6.0-windows\K4os.Compression.LZ4.dll" />
    <None Include="bin\Debug\net6.0-windows\metaimages.debug.log" />
    <None Include="bin\Debug\net6.0-windows\Newtonsoft.Json.dll" />
    <None Include="bin\Debug\net6.0-windows\OpenTK.Compute.dll" />
    <None Include="bin\Debug\net6.0-windows\OpenTK.Core.dll" />
    <None Include="bin\Debug\net6.0-windows\OpenTK.Graphics.dll" />
    <None Include="bin\Debug\net6.0-windows\OpenTK.Input.dll" />
    <None Include="bin\Debug\net6.0-windows\OpenTK.Mathematics.dll" />
    <None Include="bin\Debug\net6.0-windows\OpenTK.OpenAL.dll" />
    <None Include="bin\Debug\net6.0-windows\OpenTK.Windowing.Common.dll" />
    <None Include="bin\Debug\net6.0-windows\OpenTK.Windowing.Desktop.dll" />
    <None Include="bin\Debug\net6.0-windows\OpenTK.Windowing.GraphicsLibraryFramework.dll" />
    <None Include="bin\Debug\net6.0-windows\output\Edited_igLibrary.Core.igName_2.igz" />
    <None Include="bin\Debug\net6.0-windows\output\Edited_igLibrary.Core.igName_3.igz" />
    <None Include="bin\Debug\net6.0-windows\output\Output_0.igz" />
    <None Include="bin\Debug\net6.0-windows\output\Output_1.igz" />
    <None Include="bin\Debug\net6.0-windows\runtimes\linux-x64\native\libcimgui.so" />
    <None Include="bin\Debug\net6.0-windows\runtimes\linux-x64\native\libglfw.so.3.3" />
    <None Include="bin\Debug\net6.0-windows\runtimes\osx-arm64\native\libglfw.3.dylib" />
    <None Include="bin\Debug\net6.0-windows\runtimes\osx-x64\native\libglfw.3.dylib" />
    <None Include="bin\Debug\net6.0-windows\runtimes\osx\native\libcimgui.dylib" />
    <None Include="bin\Debug\net6.0-windows\runtimes\win-arm64\native\cimgui.dll" />
    <None Include="bin\Debug\net6.0-windows\runtimes\win-x64\native\cimgui.dll" />
    <None Include="bin\Debug\net6.0-windows\runtimes\win-x64\native\glfw3.dll" />
    <None Include="bin\Debug\net6.0-windows\runtimes\win-x86\native\cimgui.dll" />
    <None Include="bin\Debug\net6.0-windows\runtimes\win-x86\native\glfw3.dll" />
    <None Include="bin\Debug\net6.0-windows\SevenZip.dll" />
    <None Include="bin\Debug\net6.0-windows\SixLabors.ImageSharp.dll" />
    <None Include="bin\Debug\net6.0-windows\test.igz" />
  </ItemGroup>

  <Target Name="Debug|Release" AfterTargets="AfterBuild">
    <Copy SourceFiles="@(ArkFiles)" DestinationFolder="$(OutDir)/ArkCore/%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(DefaultImGuiIni)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>
  <Target Name="Debug|Release" AfterTargets="Publish">
    <Copy SourceFiles="@(ArkFiles)" DestinationFolder="$(OutDir)/publish/ArkCore/%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(DefaultImGuiIni)" DestinationFolder="$(OutDir)/publish" SkipUnchangedFiles="true" />
  </Target>
</Project>
